### ISSUE TITLE
Python3.4 equivalent?

### ISSUE THREAD

**Issue by wetneb** [syrusakbary/aiodataloader#1]
Hi!
This looks great, but I cannot use python 3.5. Do you know anything that does something similar for Python 3.4?
Thanks!

**Comment by rhaven-pinterest** [comment]
This question is now critical

Cheers

**Comment by ajhyndman** [comment]
I think @syrusakbary has another package, `promise` which includes a similar DataLoader implementation based on Promise instead of asyncio, which should make it compatible with python <=3.4.

https://github.com/syrusakbary/promise/blob/master/promise/dataloader.py

**Comment by syrusakbary** [comment]
@ajhyndman response is right. Closing the issue :)
