### ISSUE TITLE
Allow overriding get_cache_key method on subclass

### ISSUE THREAD

**Issue by dkbarn** [syrusakbary/aiodataloader#15]
I prefer to subclass DataLoader and provide an overridden batch_load_fn on the subclass, rather than passing a function into DataLoader's constructor (which feels a little too Javascript-y).

Please could the same functionality be provided for the get_cache_key function? At the moment, there is no way to override this function on a subclass because of the way the function is defaulted inside the constructor.

**Comment by markedwards** [comment]
@dkbarn, let me know if you see any issues with this solution.
