### ISSUE TITLE
Push collections.abc deprecation warning fix to pypi

### ISSUE THREAD

**Issue by dereklukacs** [syrusakbary/aiodataloader#16]
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```

I'm currently seeing this warning using version 0.2.0.

I see that this was fixed in commit 13e696e03b49b2ac33b0dc5bb8d35217d7c5053e

But this code is not available on pypi. Could a new version be released?

**Comment by dkbarn** [comment]
Has this project been abandoned?

We just need someone to push a release to pypi for this warning to go away.

**Comment by markedwards** [comment]
@syrusakbary any chance of seeing this released?

Also, does this project need maintainers?  I'm sure there are folks who would step up.  I'd like to see type hints added, for instance, and I'd be happy to contribute that.

**Comment by dereklukacs** [comment]
@syrusakbary What is the status of this package?

**Comment by twelvelabs** [comment]
@syrusakbary any chance you could publish a new release?

**Comment by markedwards** [comment]
This is now breaking in python 3.10.  Is this project abandoned or what?

Should we fork it or can a responsive maintainer be assigned?

**Comment by achimnol** [comment]
@syrusakbary If you don't have time or interest to maintain this project, would you promote another person to do it? It is now breaking many of GraphQL-based projects in Python and asyncio. Maybe we could consider moving the project to [aio-libs](https://github.com/aio-libs).

**Comment by Cito** [comment]
@markedwards @achimnol We should bring this issue up on Slack.
Would you be willing to act as maintainers if nobody else steps up?

**Comment by markedwards** [comment]
I’m for being a maintainer.  I’d like to see the code become fully typed.

**Comment by Cito** [comment]
That would be great. I have pinged Syrus and hope this project can be revived.

**Comment by markedwards** [comment]
Release 0.2.1 will happen on 2022-01-24 (Monday), and will include the commit which unbreaks python 3.10, as well as a commit that fixes a minor Readme issue.

**Comment by markedwards** [comment]
Resolved as of release 0.2.1.

**Comment by syrusakbary** [comment]
That is awesome @markedwards , could we have automatic PyPI publishing based on GH actions? That would make doing releases much easier for the future

**Comment by markedwards** [comment]
@syrusakbary Will look into that, yes.  First priority is getting test pipeline working again using GH, since the Travis setup no longer works.

**Comment by Cito** [comment]
@markedwards You can copy the workflows from graphql-relay-py. If you find things that can be improved let me know.

**Comment by achimnol** [comment]
@syrusakbary @markedwards You could refer my fork: https://github.com/lablup/aiodataloader-ng/tree/master/.github/workflows
Glad to see you came back! 🤗
