### ISSUE TITLE
Project maintaining

### ISSUE THREAD

**Issue by antonmyronyuk** [syrusakbary/aiodataloader#20]
Is it possible to move this project to [aio-libs](https://github.com/aio-libs) organization? 
Of course, I can copy this package to my project and do some needed changes locally, but I guess many people are interested in further project support and _aio_-ecosystem growth!

**Comment by antonmyronyuk** [comment]
@asvetlov @webknjaz
Do you have any thoughts on this?

**Comment by webknjaz** [comment]
Should the project get transferred, who would maintain it after the move?

**Comment by antonmyronyuk** [comment]
I guess I can do some contributions.
Also @allancaffee wanted to add typing for this package #19, and of course @syrusakbary is always welcome (if has desire and enough free time).

**Comment by webknjaz** [comment]
Somebody should have ownership over the release management, reviewing contributions and engaging with the community too. Plus the original maintainers should speak up.

**Comment by markedwards** [comment]
I'm now a maintainer, and will be pushing things forward.  After a release to unbreak python 3.10, I intend to get the code properly typed and do a more significant release.

I welcome engagement and contributions. :-)
