### ISSUE TITLE
Move aiodataloader beneath graphql-python github org?

### ISSUE THREAD

**Issue by dan98765** [syrusakbary/aiodataloader#3]
Hi @syrusakbary - since dataloader/aiodataloader are so closely tied with our graphql implementation using graphene, I got to wondering whether you'd consider moving them beneath [graphql-python](https://github.com/graphql-python) github org. Thoughts?

**Comment by zenflow** [comment]
Doesn't graphene have it's own DataLoader implementation? https://docs.graphene-python.org/en/latest/execution/dataloader/

Other than that, this library is useful for more than just graphql APIs (it can be used in plain old REST APIs too), so wouldn't it be better to live outside anything graphql-specific?

**Comment by syrusakbary** [comment]
I wanted to have the packages outside of the graphql-python org, because they might be useful in other cases outside of GraphQL (even though the main use case is probably GraphQL).

Closing the issue

**Comment by jkgenser** [comment]
We have found value out of this library in GraphQL but also outside of Graphql. We have a graph-like data model in one of our services for a "workflow", and when we load data from our sql backend and need to hydrate data from other services, we use aiodataloader to cache inter service calls.
